apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-pvc
  labels:
    app: nginx-pod-pvc
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: myvol
          mountPath: /etc/new_vol
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: pvc1
