apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeployment
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydeployment
  strategy: {}
  template:
    metadata:
      labels:
        app: mydeployment
    spec:
      containers:
      - image: nginx
        name: nginx
