apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx-app1
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: myvol
          mountPath: /etc/new_vol
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mongo-pvc-sc1
