apiVersion: v1
kind: Pod
metadata:
  labels:
    infra: aws
  name: nginx1
spec:
  nodeSelector:
    infra: aws
  containers:
  - image: nginx
    name: nginx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
