apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
        
        - matchExpressions:
          - key: infra
            operator: In
            values:
            - aws
  containers:
  - image: nginx
    name: nginx
status: {}
