apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    app.kubernetes.io/managed-by: Helm
  name: svc-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
