version: "2"
services:
  web:
    build: .
    ports:
      - "80:8080"
    links:
      - redis
    networks:
      - mynet
  redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - mynet
networks:
  mynet:
